# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
        java-package: jdk+fx 
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build Fat Cross-Platform Jar with Gradle
      run: ./gradlew jar
    - name: Upload a the Fat Cross-Platform Jar Artifact
      uses: actions/upload-artifact@v2
      with:
        name: CAViewer.jar
        path: build/libs/CAViewer.jar
    - name: Build Executable with JLink & JPackage
      run: ./gradlew jpackage
    - name: Upload a the Executable
      uses: actions/upload-artifact@v2
      with:
        name: CAViewer
        path: build/jpackage/CAViewer

  windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
        java-package: jdk+fx 
    - name: Build Executable with JLink & JPackage
      run: ./gradlew jpackage
    - name: Upload the Executable
      uses: actions/upload-artifact@v2
      with:
        name: CAViewer
        path: build/jpackage/CAViewer
        
  macOS:
    name: Build on MacOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
        java-package: jdk+fx 
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build Executable with JLink & JPackage
      run: ./gradlew jpackage
    - name: Upload the Executable
      uses: actions/upload-artifact@v2
      with:
        name: CAViewer
        path: build/jpackage/CAViewer
