# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build CAViewer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
        java-package: jdk+fx 
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build Gradle
      run: ./gradlew build
    - name: Build Executable with JLink & JPackage
      run: ./gradlew jpackage
    - shell: bash
      run: |
        ls -R
    - name: Upload the Executable
      uses: actions/upload-artifact@v2
      with:
        name: CAViewer-Linux
        path: ./build/jpackage/CAViewer

  windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
        java-package: jdk+fx
    - name: Build Gradle
      run: ./gradlew build
    - name: Build Executable with JLink & JPackage
      run: ./gradlew jpackage
    - name: Upload the Executable
      uses: actions/upload-artifact@v2
      with:
        name: CAViewer-Windows
        path: build/jpackage/CAViewer
        
  macOS:
    name: Build on MacOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
        java-package: jdk+fx 
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build Gradle
      run: ./gradlew build
    - name: Build Executable with JLink & JPackage
      run: ./gradlew jpackage
    - shell: bash
      run: |
        ls -R
    - name: Upload the Executable
      uses: actions/upload-artifact@v2
      with:
        name: CAViewer-MacOS
        path: ./build/image/CAViewer.app

  cross-platform:
    name: Build the Cross-Platform Fat Jar
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
          java-package: jdk+fx
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Gradle
        run: ./gradlew build --build-file build2.gradle
      - shell: bash
        run: |
          ls -R
      - name: Upload the Fat Cross-Platform Jar Artifact
        uses: actions/upload-artifact@v2
        with:
          name: CAViewer.jar
          path: ./build/libs/Cellular-Automaton-Viewer.jar
